use_frameworks!

platform :ios, '10.0'

target 'ttBaseCode_Example' do
  pod 'ttBaseCode', :path => '../'

  target 'ttBaseCode_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
